CREATE TABLE USUARIO (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    SENHA VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(20) NOT NULL,
    TELEFONE VARCHAR2(20),
    LOCALIZACAO VARCHAR2(100),
    FOTO_PERFIL VARCHAR2(255),
    ATIVO NUMBER(1) DEFAULT 1,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSAO NUMBER DEFAULT 0,
    CURRICULO CLOB,
    EXPERIENCIA VARCHAR2(100),
    HABILIDADES VARCHAR2(500)
);

CREATE TABLE EMPRESA (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CNPJ VARCHAR2(14) UNIQUE NOT NULL,
    DESCRICAO VARCHAR2(500),
    WEBSITE VARCHAR2(255),
    SETOR VARCHAR2(100),
    TAMANHO VARCHAR2(20),
    LOGO VARCHAR2(255),
    ATIVO NUMBER(1) DEFAULT 1,
    VERSAO NUMBER DEFAULT 0,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP
);

CREATE TABLE VAGA (
    ID NUMBER PRIMARY KEY,
    TITULO VARCHAR2(100) NOT NULL,
    DESCRICAO CLOB NOT NULL,
    TIPO VARCHAR2(20) NOT NULL,
    NIVEL VARCHAR2(20) NOT NULL,
    LOCALIZACAO VARCHAR2(100) NOT NULL,
    SALARIO NUMBER(10,2),
    REQUISITOS VARCHAR2(1000),
    EMPRESA_ID NUMBER NOT NULL,
    EMPRESA_NOME VARCHAR2(100),
    ATIVA NUMBER(1) DEFAULT 1,
    DATA_PUBLICACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSAO NUMBER DEFAULT 0,
    DATA_ATUALIZACAO TIMESTAMP,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);

CREATE TABLE CANDIDATURA (
    ID NUMBER PRIMARY KEY,
    USUARIO_ID NUMBER NOT NULL,
    VAGA_ID NUMBER NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDENTE',
    DATA_CANDIDATURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OBSERVACAO VARCHAR2(500),
    VERSAO NUMBER DEFAULT 0,
    DATA_ATUALIZACAO TIMESTAMP,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (VAGA_ID) REFERENCES VAGA(ID),
    UNIQUE (USUARIO_ID, VAGA_ID)
);

-- Sequences
CREATE SEQUENCE USUARIO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EMPRESA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE VAGA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CANDIDATURA_SEQ START WITH 1 INCREMENT BY 1;